"""Added description to prompts tables

Revision ID: 17876c4ea29d
Revises: 2884b880c101
Create Date: 2023-04-17 14:03:44.941125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17876c4ea29d'
down_revision = '2884b880c101'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('description', sa.String(length=4096), nullable=True))
    op.execute("UPDATE prompts SET description = '<empty description>'")
    op.alter_column('prompts', 'description', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'description')
    # ### end Alembic commands ###
