"""Removed description and prompt_text columsn from prompt table

Revision ID: 22343e0c71fe
Revises: 5e2265e6b9d7
Create Date: 2023-04-17 23:18:49.364515

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22343e0c71fe"
down_revision = "5e2265e6b9d7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompts", "prompt_text")
    op.drop_column("prompts", "description")
    op.drop_index("ix_prompts_version_prompt_id", table_name="prompts_revisions")
    op.create_index(
        op.f("ix_prompts_revisions_prompt_id"),
        "prompts_revisions",
        ["prompt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompts_revisions_prompt_id"), table_name="prompts_revisions")
    op.create_index(
        "ix_prompts_version_prompt_id", "prompts_revisions", ["prompt_id"], unique=False
    )
    op.add_column(
        "prompts",
        sa.Column(
            "description", sa.VARCHAR(length=4096), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "prompts",
        sa.Column(
            "prompt_text", sa.VARCHAR(length=4096), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
