"""Added revision_id column to prompts_history table

Revision ID: 93a96fad9c69
Revises: 22343e0c71fe
Create Date: 2023-04-17 23:35:54.302055

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "93a96fad9c69"
down_revision = "22343e0c71fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_prompts_revision_id", table_name="prompts")
    op.drop_constraint("prompts_revision_id_fkey", "prompts", type_="foreignkey")
    op.drop_column("prompts", "revision_id")
    op.add_column(
        "prompts_history", sa.Column("revision_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_prompts_history_revision_id"),
        "prompts_history",
        ["revision_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "prompts_history", "prompts_versions", ["revision_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "prompts_history", type_="foreignkey")
    op.drop_index(op.f("ix_prompts_history_revision_id"), table_name="prompts_history")
    op.drop_column("prompts_history", "revision_id")
    op.add_column(
        "prompts",
        sa.Column("revision_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "prompts_revision_id_fkey",
        "prompts",
        "prompts_versions",
        ["revision_id"],
        ["id"],
    )
    op.create_index("ix_prompts_revision_id", "prompts", ["revision_id"], unique=False)
    # ### end Alembic commands ###
