"""Added cascade to PromptRecord

Revision ID: d1d52e5c9c0d
Revises: fc8341b0214e
Create Date: 2023-04-18 17:23:47.423242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d52e5c9c0d'
down_revision = 'fc8341b0214e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts_revisions', 'prompt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prompts_revisions', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prompts_revisions', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('prompts_revisions', 'prompt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
