"""Initial set of tables

Revision ID: d972eee83c94
Revises:
Create Date: 2023-04-18 20:43:32.481398

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d972eee83c94"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompts_slug"), "prompts", ["slug"], unique=False)
    op.create_index("ix_slug_is_active", "prompts", ["slug", "is_active"], unique=False)
    op.create_table(
        "prompts_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=False),
        sa.Column("prompt_text", sa.String(length=4096), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompts_revisions_prompt_id"),
        "prompts_revisions",
        ["prompt_id"],
        unique=False,
    )
    op.create_table(
        "prompts_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt_id", sa.Integer(), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["prompt_id"],
            ["prompts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["prompts_revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prompts_history_prompt_id"),
        "prompts_history",
        ["prompt_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prompts_history_revision_id"),
        "prompts_history",
        ["revision_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompts_history_revision_id"), table_name="prompts_history")
    op.drop_index(op.f("ix_prompts_history_prompt_id"), table_name="prompts_history")
    op.drop_table("prompts_history")
    op.drop_index(
        op.f("ix_prompts_revisions_prompt_id"), table_name="prompts_revisions"
    )
    op.drop_table("prompts_revisions")
    op.drop_index("ix_slug_is_active", table_name="prompts")
    op.drop_index(op.f("ix_prompts_slug"), table_name="prompts")
    op.drop_table("prompts")
    # ### end Alembic commands ###
