VARIABLE_MAX_NAME_LENGTH = 2048

##
##  Error Codes
##
VARIABLE_ALREADY_EXISTS = "VARIABLE_ALREADY_EXISTS"
VARIABLE_DOES_NOT_EXIST = "VARIABLE_DOES_NOT_EXIST"
VARIABLE_ENTITY_TOO_LARGE = "VARIABLE_ENTITY_TOO_LARGE"
VARIABLE_INVALID_PERMISSION = "VARIABLE_INVALID_PERMISSION"
