MAX_NAME_LENGTH = 256
MAX_DISPLAY_NAME_LENGTH = 256
MAX_DESCRIPTION_LENGTH = 1024

EMAIL_COLUMN_LENGTH = 512
HASHED_PASSWORD_COLUMN_LENGTH = 256


RECORD_ALREADY_EXISTS = "RECORD_ALREADY_EXISTS"
RECORD_DOES_NOT_EXIST = "RECORD_DOES_NOT_EXIST"


# Route Response fixed strings
INSUFFICIENT_CREDENTIALS = "INSUFFICIENT_CREDENTIALS"
"""
Used when credentials match but the user is not permitted to perform an action.
Paired with a HTTP 403 Forbidden
"""

INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
"""
Used when credentials do not match or cannot be resolved.
Paired with a HTTP 401 Unauthorized
"""

UNAUTHENTICATED_REQUEST = "UNAUTHENTICATED_REQUEST"
INVALID_DATA = "INVALID_DATA"
INVALID_INPUT = "INVALID_INPUT"
